apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
type: Opaque
data:
  APP_PORT: {{ default 3000 .Values.service.port | toString | b64enc }}
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
